divert(`-1')
changecom(`!')
define(BG1, navy)
define(XPMFILE,)
define(FONT, Mono-7)
define(OUTLINE, wheat)
define(WARN, orange)
define(CRIT, red)
define(DEAD, #333333)
define(FIELD0, aquamarine)
define(FIELD1, seagreen)
define(FIELD2, yellow)
define(FIELD3, orange)
define(FIELD4, red)
define(FIELD5, lightblue)
define(FIELD6, orange red)
define(FIELD7, purple)
define(FIELD8, blue)
define(FIELD9, gold)
define(FIELD10, red)
define(LABEL1, wheat)
define(LABEL2, wheat)
divert(`0')dnl
